### ISSUE TITLE
Не реагирует бот в Telegram

### ISSUE THREAD

**Issue by SurPaul** [steeply/gbot-trader#1]
Сделал всё чётко по инструкции. worker запущен, правильный ID указан, но бот всё равно молчит.

**Comment by steeply** [comment]
Здравствуйте.
1. Убедитесь, что вы пишите именно вашему боту telegram для GBot, а не BotFather.
2. Бот отвечает только на перечисленные команды. Если вы с умели получить ваш Id то Gbot успешно отвечает.
3. Для запуска панели меню необходимо отправить команду /start

Пожалуйста, используйте группу в [Skype](https://join.skype.com/ckbfsxCIYrG2), сообщество ответит куда быстрее и поможет разобраться с настройками.
