### ISSUE TITLE
Can not run Poloniex exchange

### ISSUE THREAD

**Issue by toanalien** [steeply/gbot-trader#11]
> node ./build/server

09:59:15 - warn: -----------------------------------
09:59:15 - warn: Триал версия с ограничениями!
09:59:15 - warn: Только торговые пары с BTC!
09:59:15 - warn: Ограничение депозита 0.05 BTC!
09:59:15 - warn: -----------------------------------
09:59:15 - info: GBot Trader starting...
09:59:15 - info: Exchange: POLONIEX | v.1.2.8
09:59:26 - error: Ошибка получения данных с сервера!
Request a list of orders! Error: Poloniex error 422: . Nonce must be greater than 15059084699810000. You provided 150700676597800.

**Comment by steeply** [comment]
Use new api keys
