### ISSUE TITLE
Question: error on start

### ISSUE THREAD

**Issue by sharkpd** [steeply/gbot-trader#2]
Hi, 
I have configured the KEY, SECRET, TELEGRAM_TOKEN, EXCHANGE (bittrex), NAME_COIN, and NAME_COIN_TWO environment variables and got the TELEGRAM_ID that I then configured as an environment variable.
When I run npm start with the obtained TELEGRAM_ID, I have the following error:

> node ./build/server

19:00:19 - info: GBot Trader starting...
19:00:19 - info: Exchange: BITTREX | v.0.17.2
19:00:19 - error: Error getting parameters from the server!
Not valid pair

Can I activate a debug or advanced log to understand where I was wrong?

**Comment by steeply** [comment]
For BITTREX  and Poloniex change the name of the pair opposite. BTC/USDT -> USDT/BTC
