### ISSUE TITLE
Setup SMTP mail

### ISSUE THREAD

**Issue by toanalien** [steeply/gbot-trader#21]
I don't see email error notification config for port. Which port default for smtp email?

**Comment by steeply** [comment]
port: 465

**Comment by toanalien** [comment]
Is `- error: Err: No money! Required minimum balance: 0.001` an error? I didn't receive any email notification.

**Comment by steeply** [comment]
Notification to the mail comes only while the bot is running. At start they are not present. I will add it in the next version.
