### ISSUE TITLE
How to config size of order?

### ISSUE THREAD

**Issue by toanalien** [steeply/gbot-trader#22]
I see the size of each order only 0.001 BTC, how do I adjust this config? Thank you.

**Comment by steeply** [comment]
The size of the order is determined automatically, based on the size of the deposit, the number of orders, the Martingale size used, etc.

There are parameters SIZE_FIRST_ORDERS_CURRENCY and SIZE_FIRST_ORDERS_PERCENT but they are not available in the Trial version.

Write to the group. The group is in Russian, but there are people who know English, they will help you configure the configuration: https://telegram.me/gbottrader_chat

**Comment by toanalien** [comment]
Thank you!
