### ISSUE TITLE
Network errors Bitfinex

### ISSUE THREAD

**Issue by ernestp** [steeply/gbot-trader#25]
I set bigger delays, but not sure if it even taken into account, restart time set to 90 sec, but bot restarting with 30 sec interval (I use 'export' to set vars in unix env). 

export DELAY_REQUEST_API=1500
export DELAY_BETWEEN_MODULES=2
export RESTART_TRADER_TIME=90

`
23:21:13 - error: ErrorData: 429

23:21:13 - warn: restart after 30 sec ...

23:21:43 - warn: trader restart

23:21:44 - error: ErrorData: 429

23:21:44 - warn: restart after 30 sec ...

23:22:14 - warn: trader restart

23:24:22 - error: ErrorData: 520

23:24:22 - warn: restart after 90 sec ...

23:25:52 - warn: trader restart

23:27:00 - error: ErrorData: 520

23:27:00 - warn: restart after 90 sec ...

23:28:30 - warn: trader restart

23:30:01 - error: ErrorData: 429

23:30:01 - warn: restart after 30 sec ...
`

It seems to workaround this timeout should be set to bigger value every failure, for example
1st retry 30 sec
2nd retry 45 sec
3rd retry 60 sec
etc

Also probably there is User Agent should be set to same value as browser or mobile bitfinex app.

**Comment by steeply** [comment]
export DELAY_BETWEEN_MODULES=10 or more

**Comment by ernestp** [comment]
tried 30, does not help, seems not today
