### ISSUE TITLE
EXMO - some pairs are not shows the quotes

### ISSUE THREAD

**Issue by pyppy** [steeply/gbot-trader#3]
Hi,
I met a problem at EXMO I tried to get current quote of ETH/RUB but the bot told me that it is not avaliable . on the button it shows ETH/RUR but in EXMO it should be ETH/RUB - probably this is a reason of a mistake. I also tried some other pairs to check and had similar situation with RUB pair. Please fix it.
Thank a lot.

**Comment by steeply** [comment]
We know about this error.
The bug is fixed in the new version. 
Thank you for contacting us.
