### ISSUE TITLE
How to use the whole account on every restart

### ISSUE THREAD

**Issue by Daedalus-code** [steeply/gbot-trader#34]
How to use the whole account every time bot restarts? (The PAIRS you are using.)
Like not only use the reserves and end up splitting it up so bad it's just fractions left for trading. 👀 

This is the config I use:

```
export DEPOSIT_LIMIT=70%
export EXCHANGE=Poloniex
export NAME_COIN=btc
export NAME_COIN_TWO=usdt
export COUNT_ORDERS=20
export OFFSET_FIRST_ORDERS_PERCENT=0.01
export ONE_ORDERS_OFFSET=0.4
export ONE_ORDERS_PROFIT_PERCENT=0.3
export ONE_ORDERS_SELL=true
export QUANTITY_ORDERS_IN_BLOCKS=5
export RANGE_OFFSET=15
export SIZE_ORDERS_MARTINGALE=20
``` 

That ends up with 30% Reserved and that's fine, but BTC is at 100% and it's kept away if I restart the bot.. Im not really understanding the configuration.

Im trying to run the bot and then stop it after a certain limit is met and then restart it and let the bot use the whole account on USDT and BTC that are there and create new 30% reserve each time.

Now it's just eating up the reserves into tiny satoshis 🤔 And then I have to stop the bot, login to Poloniex and sell all into USDT again, restart bot so the bot can use the "whole account" on those two PAIRS I use.

**Comment by steeply** [comment]
Try 
export PERMANENT_DEPOSIT=true

**Comment by Daedalus-code** [comment]
Thank you for answer! Was looking at that on README

it still says ``Closing of all orders`` now two times restarting the bot with ``export PERMANENT_DEPOSIT=true``

```
export PERMANENT_DEPOSIT=true
export DEPOSIT_LIMIT=70%
export EXCHANGE=Poloniex
export NAME_COIN=btc
export NAME_COIN_TWO=usdt
export COUNT_ORDERS=20
export OFFSET_FIRST_ORDERS_PERCENT=0.01
export ONE_ORDERS_OFFSET=0.4
export ONE_ORDERS_PROFIT_PERCENT=0.3
export ONE_ORDERS_SELL=true
export QUANTITY_ORDERS_IN_BLOCKS=5
export RANGE_OFFSET=15
export SIZE_ORDERS_MARTINGALE=20
```

**Comment by steeply** [comment]
When launched, the bot closes all orders. This is how it calculates the total balance and makes deposit reserves. Then it re-places orders based on the specified configuration.

You can prohibit closing orders at the start. But then all orders that were on the market at the start will be ignored and will not be taken into account during operation. The orders that were opened during the current bot session will be taken into account

export IGNORE_ORDERS_AT_START=true

Although I may have misunderstood your problem

**Comment by Daedalus-code** [comment]
``export IGNORE_ORDERS_AT_START=true`` Interesting, I just want it all in play, don't leave it out.
It can close orders thats fine, really, I just want it to know the total balance on those two pairs and use it, every time.

Thank you for answering.

**Comment by Daedalus-code** [comment]
A rule that would move everything into one pair (USDT) when it starts, from those two pair you setup of course, then it can start over with it's calculations with everything in USDT.
I don't want to sound rude 🙈 kinda need a option like this cause I love the idea to build up reserves.
Amazing bot btw, Thank you for the trial version, learned a lot and had a lot of fun.

**Comment by steeply** [comment]
The transfer of the deposit at the start of the bot to one trading currency is specifically left to the discretion of the user.
Since it is not known at what price and how the user wants to make the conversion

**Comment by Daedalus-code** [comment]
I know it's the bot that will make that sell order and turn it into USDT for example, If the user wants that option it's our own risk right? Cause I kinda do it every time now for two years.

**Comment by Daedalus-code** [comment]
Well it can be a bigger problem the bigger the order is and longer the bot has to wait to fulfil it enough to start..
Im not really sure other ways I can do it, but you are right.

Im restarting the bot when the market is idling for a certain time and the bot are above the "buy order" and earned enough and then I stop the bot, canceling orders, selling everything into USDT and then restart the bot and then it builds a bigger reserve and have some extra to trade with.

**Comment by Daedalus-code** [comment]
When the bot does it's last big sell at top and then has the ``USDT`` in total for a moment, can the bot do the "recalculations" again? and then create a new set ``Reserved Amount`` from that total amount in ``USDT``? 

So like do that "process" in-between before it continues again? 🙈
