### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by micronull** [steeply/gbot-trader#5]
Сделал docker.
Протестите пожалуйста, если все нормально, то не плохо было бы добавить в readme. 
https://gist.github.com/De-Luxis/82a0dd7055ea9b261b29c33de828f03a

**Comment by steeply** [comment]
Извените, у меня нет возможности запустить докер. Если docerfiles рабочий я могу его пример вставить в Fag, только для этого нужен универсальный пример с пояснениями.
